### ISSUE TITLE
Quick example of using API to login and create a link

### ISSUE THREAD

**Issue by adhawkins** [JackBailey/Lynx#16]
Are you able to give a quick example of how to use the API to login and create a short link?

I see that using an API key is in the TODO list, what is the status of this? Can I use an API key to login instead of username / password?

**Comment by JackBailey** [comment]
The API key is currently set up to use it with sharex so you can do the following:

Make a POST request to /api/sharex with a multiform body with `secret` set to your API key, and `url` set to your source URL that you want to shorten. The API will then respond with:
```
{ 
                 success: true, 
                 url: `${domain}/${slug}`, 
}
```

**Comment by adhawkins** [comment]
Perfect!

I was looking at the other files in the source under 'api'. Hadn't considered looking at the sharex one.

**Comment by JackBailey** [comment]
Great, glad I could help!
